=== wgk997/mule4-dump/studio-workspace/apdw2-flights-starter/target/META-INF/mule-src/apdw2-flights/src/test/resources/flights-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
            "airline": {
              "description": "The airline name",
              "type": "string"
            },
            "flightCode": {
              "description": "The flight code",
              "type": "string"
            },
            "fromAirportCode": {
              "description": "The three letter airport code for the airport of origination",
              "type": "string"
            },
            "toAirportCode": {
              "description": "The three letter airport code for the airport of destination",
              "type": "string"
            },
            "departureDate": {
              "description": "The flight departure date",
              "type": "string"
            },
            "emptySeats": {
              "description": "The number of available seats",
              "type": "integer"
            },
            "totalSeats": {
              "description": "The total number of seats",
              "type": "integer"
            },
      		"price": {
              "description": "The flight price",
              "type": "integer"
            },
            "planeType": {
              "description": "The plane type",
              "type": "string"
            }
  }
}

=== wgk997/mule4-dump/studio-workspace/asx-apdev-flights-ws/src/test/resources/sample_data/json_1.json
[{
  "airline": "United",
  "flightCode": "ER38sd",
  "fromAirportCode": "LAX",
  "toAirportCode": "SFO",
  "departureDate": "May 21, 2016",
  "emptySeats": 0,
  "totalSeats": 200,
  "price": 199,
  "planeType": "Boeing 737"
},
{
  "airline": "American",
  "flightCode": "ER38sd",
  "fromAirportCode": "LAX",
  "toAirportCode": "DFW",
  "departureDate": "May 21, 2016",
  "emptySeats": 0,
  "totalSeats": 200,
  "price": 199,
  "planeType": "Boeing 737"
}
]
